x-postgres-common:
  &postgres-common
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  restart: unless-stopped
  healthcheck:
    test: 'pg_isready -U postgres --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5
  command: |
    postgres 
    -c wal_level=logical
    -c hot_standby=on 
    -c max_wal_senders=10 
    -c max_replication_slots=10 
    -c hot_standby_feedback=on

services:
  master:
    <<: *postgres-common
    ports:
      - 5430:5432
    image: postgres:16.1-alpine3.19
    container_name: logrepl_pg_master
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./01_init_master.sql:/docker-entrypoint-initdb.d/01_init_master.sql
      - logrepl_pg_master-data:/var/lib/postgresql/data
  replica1:
    <<: *postgres-common
    ports:
      - 5431:5432
    image: postgres:15.5-alpine3.19
    container_name: logrepl_pg_replica1
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./01_init_replica1.sql:/docker-entrypoint-initdb.d/01_init_replica1.sql
      - logrepl_pg_replica1-data:/var/lib/postgresql/data
  replica2:
    <<: *postgres-common
    ports:
      - 5432:5432
    image: postgres:14.10-alpine3.19
    container_name: logrepl_pg_replica2
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./01_init_replica2.sql:/docker-entrypoint-initdb.d/01_init_replica2.sql
      - logrepl_pg_replica2-data:/var/lib/postgresql/data
volumes:
  logrepl_pg_master-data:
    name: logrepl_pg_master-data
  logrepl_pg_replica1-data:
    name: logrepl_pg_replica1-data
  logrepl_pg_replica2-data:
    name: logrepl_pg_replica2-data

